# SPDX-FileCopyrightText: 2024-2025 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
# SPDX-License-Identifier: Apache-2.0
---
# -- Additional custom annotations to add to all deployed kubernetes objects
additionalAnnotations: {}

# -- Additional custom labels to add to all deployed kubernetes objects
additionalLabels: {}


config:
  global:
    # -- Additional custom annotations to add to all generated alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all generated alerts
    additionalAlertLabels: {}
    # -- How long an alert query must return results in order for alerts to be considered firing
    alertsFiringFor: 15m

  services:
    # -- Enable alerts for shared opendesk services
    enabled: true
    # -- Additional custom annotations to add to all shared opendesk services related alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all shared opendesk services related alerts
    additionalAlertLabels: {}
    # -- Regex which identifies namespaces that contain shared opendesk services; defaults to this helm charts namespace
    # -- Namespace in which shared opendesk services are deployed; defaults to this helm charts namespace.
    namespace: ""
    selectors:
      # -- Regex which identifies pods belonging to shared opendesk services by name
      pods: "clamav-.+|intercom-service-.+|mariadb-.+|memcached-.+|minio-.+|postfix-.+|postgresql-.+|redis-.+"
      # -- Regex which identifies persistent volume claims belonging to shared opendesk services by name
      pvcs: "clamav-.+|data-mariadb-.+|data-postgresql-.+|dovecot|minio|postfix"
      # -- Regex which identifies jobs belonging to shared opendesk services by name
      jobs: "mariadb-bootstrap|minio-provisioning|postgresql-bootstrap"
      # -- Regex which identifies endpoints belonging to shared opendesk services by name
      endpoints: "clamav-.+|intercom-service|mariadb|memcached|minio|postfix|postgresql|redis-.+"
  
  element:
    # -- Enable alerts for element/matrix/synapse
    enabled: true
    # -- Additional custom annotations to add to all element/matrix/synapse related alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all element/matrix/synapse related alerts
    additionalAlertLabels: {}
    # -- Namespace in which matrix/synapse is deployed; defaults to this helm charts namespace.
    namespace: ""
    selectors:
      # -- Regex which identifies pods belonging to element/matrix/synapse by name
      pods: "matrix-.+|opendesk-synapse-.+"
      # -- Regex which identifies persistent volume claims belonging to element/matrix/synapse by name
      pvcs: "matrix-.+|media-opendesk-synapse-.+"
      # -- Regex which identifies jobs belonging to element/matrix/synapse by name
      jobs: "opendesk-matrix-.+|matrix-neodatefix-.+"
      # -- Regex which identifies endpoints belonging to element/matrix/synapse by name
      endpoints: "matrix-.+|opendesk-element|opendesk-synapse.+"

  cryptpad:
    # -- Enable alerts for diagrams/cryptpad
    enabled: true
    # -- Additional custom annotations to add to all diagrams/cryptpad related alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all diagrams/cryptpad related alerts
    additionalAlertLabels: {}
    # -- Namespace in which diagrams/cryptpad is deployed; defaults to this helm charts namespace.
    namespace: ""
    selectors:
      # -- Regex which identifies pods belonging to diagrams/cryptpad by name
      pods: "cryptpad-.+"
      # -- Regex which identifies persistent volume claims belonging to diagrams/cryptpad by name
      pvcs: ""
      # -- Regex which identifies jobs belonging to diagrams/cryptpad by name
      jobs: ""
      # -- Regex which identifies endpoints belonging to diagrams/cryptpad by name
      endpoints: "cryptpad"

  nextcloud:
    # -- Enable alerts for nextcloud
    enabled: true
    # -- Additional custom annotations to add to all nextcloud related alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all nextcloud related alerts
    additionalAlertLabels: {}
    # -- Namespace in which nextcloud is deployed; defaults to this helm charts namespace.
    namespace: ""
    selectors:
      # -- Regex which identifies pods belonging to nextcloud by name
      pods: "opendesk-nextcloud-aio.*|open-xchange-nextcloud-.*"
      # -- Regex which identifies persistent volume claims belonging to nextcloud by name
      pvcs: "minio"
      # -- Regex which identifies jobs belonging to nextcloud by name
      jobs: "opendesk-nextcloud-.+"
      # -- Regex which identifies endpoints belonging to nextcloud by name
      endpoints: "minio|opendesk-nextcloud-aio"

  oxAppSuite:
    # -- Enable alerts for OpenXChange
    enabled: true
    # -- Additional custom annotations to add to all OpenXChange related alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all OpenXChange related alerts
    additionalAlertLabels: {}
    # -- Namespace in which OpenXChange is deployed; defaults to this helm charts namespace.
    namespace: ""
    selectors:
      # -- Regex which identifies pods belonging to OpenXChange by name
      pods: "open-xchange.*|ox-connector.*|opendesk-open-xchange-.*"
      # -- Regex which identifies persistent volume claims belonging to OpenXChange by name
      pvcs: "ox-.+"
      # -- Regex which identifies jobs belonging to OpenXChange by name
      jobs: "opendesk-open-xchange-.+"
      # -- Regex which identifies endpoints belonging to OpenXChange by name
      endpoints: "open-xchange-.+"

  xwiki:
    # -- Enable alerts for xwiki
    enabled: true
    # -- Additional custom annotations to add to all xwiki related alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all xwiki related alerts
    additionalAlertLabels: {}
    # -- Namespace in which xwiki is deployed; defaults to this helm charts namespace.
    namespace: ""
    selectors:
      # -- Regex which identifies pods belonging to xwiki by name
      pods: "xwiki-.+"
      # -- Regex which identifies persistent volume claims belonging to xwiki by name
      pvcs: "xwiki-data-.+"
      # -- Regex which identifies jobs belonging to xwiki by name
      jobs: ""
      # -- Regex which identifies endpoints belonging to xwiki by name
      endpoints: "xwiki"

  nubus:
    # -- Enable alerts for nubus
    enabled: true
    # -- Additional custom annotations to add to all nubus related alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all nubus related alerts
    additionalAlertLabels: {}
    # -- Namespace in which nubus is deployed; defaults to this helm charts namespace.
    namespace: ""
    selectors:
      # -- Regex which identifies pods belonging to nubus by name
      pods: "ums-.+"
      # -- Regex which identifies persistent volume claims belonging to nubus by name
      pvcs: ".+-ums-.+"
      # -- Regex which identifies jobs belonging to nubus by name
      jobs: "ums-.+|opendesk-keycloak-.+"
      # -- Regex which identifies endpoints belonging to nubus by name
      endpoints: "ums-.+"

  openproject:
    # -- Enable alerts for OpenProject
    enabled: true
    # -- Additional custom annotations to add to all OpenProject related alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all OpenProject related alerts
    additionalAlertLabels: {}
    # -- Namespace in which OpenProject is deployed; defaults to this helm charts namespace.
    namespace: ""
    selectors:
      # -- Regex which identifies pods belonging to OpenProject by name
      pods: "openproject-.+"
      # -- Regex which identifies persistent volume claims belonging to OpenProject by name
      pvcs: "openproject-.+"
      # -- Regex which identifies jobs belonging to OpenProject by name
      jobs: "opendesk-openproject-.+"
      # -- Regex which identifies endpoints belonging to OpenProject by name
      endpoints: "openproject"

  jitsi:
    # -- Enable alerts for jitsi
    enabled: true
    # -- Additional custom annotations to add to all jitsi related alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all jitsi related alerts
    additionalAlertLabels: {}
    # -- Namespace in which jitsi is deployed; defaults to this helm charts namespace.
    namespace: ""
    selectors:
      # -- Regex which identifies pods belonging to jitsi by name
      pods: "jitsi-.*|opendesk-jitsi-.*"
      # -- Regex which identifies persistent volume claims belonging to jitsi by name
      pvcs: "prosody-data-jitsi-.+"
      # -- Regex which identifies jobs belonging to jitsi by name
      jobs: "jitsi-opendesk-jitsi"
      # -- Regex which identifies endpoints belonging to jitsi by name
      endpoints: "jitsi-.+"

  collabora:
    # -- Enable alerts for collabora
    enabled: true
    # -- Additional custom annotations to add to all collabora related alerts
    additionalAlertAnnotations: {}
    # -- Additional custom labels to add to all collabora related alerts
    additionalAlertLabels: {}
    # -- Namespace in which collabora is deployed; defaults to this helm charts namespace.
    namespace: ""
    selectors:
      # -- Regex which identifies pods belonging to collabora by name
      pods: "collabora-.+"
      # -- Regex which identifies persistent volume claims belonging to collabora by name
      pvcs: ""
      # -- Regex which identifies jobs belonging to collabora by name
      jobs: ""
      # -- Regex which identifies endpoints belonging to collabora by name
      endpoints: "collabora"

